### ISSUE TITLE
PHP 8.1 Issues

### ISSUE THREAD

**Issue by ecosmox36** [BrainAppeal/t3monitor#11]
We have some PHP Warnings here:

Enviroment:

- TYPO3 11.5.20
- PHP Version 8.1.12
- t3monitor 1.2.14

Warnings:

```
Undefined array key "log" in /t3monitor/Classes/Reports/SysLog.php line 92 	
Undefined array key "charset" in /t3monitor/Classes/Reports/SysLog.php line 92 	
Undefined array key "cache" in /t3monitor/Classes/Reports/SysLog.php line 92 	
Undefined array key "extensionmanager" in /t3monitor/Classes/Reports/SysLog.php line 92 	
Undefined array key "" in /t3monitor/Classes/Reports/SysLog.php line 92 	
Undefined array key "lock" in /t3monitor/Classes/Reports/SysLog.php line 92 	
Undefined array key "session" in /t3monitor/Classes/Reports/SysLog.php line 92 
```
Guess the reason is a loop

**Comment by bahammes** [comment]
Hello,

thank you for reporting the bug.
The warnings occur during the calculation of the subdirectory sizes of the /var dir.
A check was missing, if the array key has been set before.

We have fixed the array warnings in Release 1.2.15

https://github.com/BrainAppeal/t3monitor
https://extensions.typo3.org/extension/t3monitor
