### ISSUE TITLE
RootPageId of Site is not used to initialize $pageArguments (TYPO3 12)

### ISSUE THREAD

**Issue by nlehmkuhl** [BrainAppeal/t3monitor#12]
Instead of using the variable $rootPageId (set in line 67), a hardcoded 1 is passed as pageId in line 72.

https://github.com/BrainAppeal/t3monitor/blob/63cc1f8c5fc187d00f4799d4695dc652c54c2a0a/Classes/CoreApi/TYPO3Version12/CoreApi.php#L72

**Comment by bahammes** [comment]
Thank you for reporting the issue.

The $rootPageId is now assigned to the PageArguments in [Release 2.0.1](https://github.com/BrainAppeal/t3monitor/releases/tag/2.0.1)

The value of the page id in the PageArguments is actually not important, we only need to make sure, that the required $GLOBALS['XYZ'] objects are set, so the reports can be generated.
That is why the fallback value for $rootPageId is set to 1.
But obviously it makes sense to set the correct root page, if we have the value.

**Comment by nlehmkuhl** [comment]
Thanks for fixing!
The value might not be important but the page must exist. - I got an exception at that line, because the page with uid=1 is marked deleted in the database of this installation...
