### ISSUE TITLE
Debug code active in Class DataResponseHandler of version 2.0.2 when installed via composer 

### ISSUE THREAD

**Issue by nlehmkuhl** [BrainAppeal/t3monitor#13]
Class DataResponseHandler contains debug code in function createResponse: 

 ```
echo '<pre>$data: '.print_r($data, true).'</pre>';
 die('TEST');//TODO: DEBUG
```

This prevents the instance from reporting...

**Comment by bahammes** [comment]
Thank you for reporting the issue.

We have removed the debug output in release v2.0.3:
https://github.com/BrainAppeal/t3monitor/releases/tag/2.0.3
