### ISSUE TITLE
Invalid eID

### ISSUE THREAD

**Issue by ecosmox36** [BrainAppeal/t3monitor#2]
Hi,
Testing with
TYPO3 10.4.12
t3monitor 1.2.5
under using a demo testaccount

**On the Managemant Dashboard:**
If i click the "test website button", there following Request is fired up: 

/?eID=brainmonitor&secret=#################&only_check=1

Inside the ext_localconf.php there are conditions to create the right eID, but the script will register the eID "t3monitor" not the required eID "brainmonitor", so the request is invalid.

My Workaround at this Time, is to duplicate the needed line inside the ext_localconf.php to register the needed eID:
```php
 $GLOBALS['TYPO3_CONF_VARS']['FE']['eID_include']['t3monitor'] = 'Tx_T3monitor_Service_Dispatcher::processRequest';
 $GLOBALS['TYPO3_CONF_VARS']['FE']['eID_include']['brainmonitor'] = 'Tx_T3monitor_Service_Dispatcher::processRequest';
```

**Comment by brain-appeal** [comment]
Hello.
Thanks for pointing out this issue.
We fixed it now. This was on the server side of the t3monitor and not in the extension.
It should work now.
