### ISSUE TITLE
function write() on null

### ISSUE THREAD

**Issue by ecosmox36** [BrainAppeal/t3monitor#4]
Tested with two instances:

TYPO3 9.5.31
PHP Version 7.3.33

TYPO3 9.5.33
PHP Version 7.2.34

Error Message:

`Call to a member function write() on null | Error thrown in file /kunden/234301_90402/websites/customer.dev/typo3_files/typo3_src-9.5.31/typo3/sysext/install/Classes/Updates/AbstractUpdate.php in line 274. Requested URL: https://www.MYDOMAIN.de/?eID=t3monitor&secret=4d0596745985ba191ddeb5aa46fc62d3&reports=security,installed_extensions,sys_log,system,install_tool,database&last_check=1646089211`

OR

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function write() on null | Error thrown in file /html/public/typo3/sysext/install/Classes/Updates/AbstractUpdate.php in line 274. Requested URL: https://www.MYDOMAIN.com/?eID=t3monitor&secret=82be1bdead1ec6334cde2bce4a67f33d&reports=security,installed_extensions,sys_log,system,install_tool,database&last_check=1648677630`

We have others 9.5ers that dosnt show error like this, any hints?

**Comment by bahammes** [comment]
The T3Monitor is searching for unfinished UpgradeWizards.
There was a check missing, if the Upgrade-Wizard implements TYPO3\CMS\Install\Updates\ChattyInterface and therefore requires the reference to an OutputInterface.
The bug is fixed in the current master branch / v.1.29
