### ISSUE TITLE
Missing Core Version

### ISSUE THREAD

**Issue by ecosmox36** [BrainAppeal/t3monitor#7]
Relevant TYPO3 Versions: 10.4 + 11.5
t3monitor extension:1.2.10

Four of our Sites dosnt show the TYPO3 Version anymore 

Right place here?

Any Hints?

**Comment by bahammes** [comment]
Thank you for reporting the issue.

This has also been fixed in v1.2.11 of t3monitor.
TER: https://extensions.typo3.org/extension/t3monitor
