### ISSUE TITLE
Missing or wrong PHP Version

### ISSUE THREAD

**Issue by ecosmox36** [BrainAppeal/t3monitor#8]
TYPO3 9.5 - 11.5
t3monitor: 1.2.10

In the Adminpanel: most of the sites dosn't show the PHP Version at the list view 

Right Place here?

Any hints?

**Comment by bahammes** [comment]
Thank you for reporting the issue.

If EXT:reports is installed, only the system information from EXT:reports were used.
These reports used to contain the PHP version, but don't any more.
We updated EXT:t3monitor, so the PHP and TYPO3-Core versions are always set in the t3monitor reports, independently of EXT:reports.

We fixed the issue and released v1.2.11 of t3monitor.
TER: https://extensions.typo3.org/extension/t3monitor
