### ISSUE TITLE
TER-Link not working

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [BrainAppeal/t3monitor#9]
Hi all, 

e.g. for extension mask, the link to TER at the bottom of the extension details dropdown is not working. 

Link leads to: https://extensions.typo3.org/extension/mask/current/

should lead to: https://extensions.typo3.org/extension/mask/

I was checking other extensions and couldn't find that link, e.g. news exteions. But I think it is very useful - could it be integrated for all extensions?

thx and best
Benjamin

**Comment by bahammes** [comment]
Hello,

thank you for reporting the bug.

We have fixed the TER link targets in the T3Monitor backend.
The TER link is now displayed for all TER extensions.

**Comment by vb-benjamin-eyring** [comment]
Thanks for the quick fix :-)!
